### PR TITLE
Feature: ConfirmChannel support

### PR DESCRIPTION
**Pull request by stepanho**
Besides Channel class, amqplib uses ConfirmChannel class. See [docs](https://amqp-node.github.io/amqplib/channel_api.html#confirmchannel) for explanations.

### CODE REVIEW

**Review by sempasha — APPROVED** [review]

**Comment by mkls** [comment]
There seems to be a conflict with this one, can you take a look at it please?

**Comment by stepanho** [comment]
> There seems to be a conflict with this one, can you take a look at it please?

@mkls Resolved, now It can be merged too

**Comment by sempasha** [comment]
@mkls could you, please, release new package version after merge?

**Comment by mkls** [comment]
I've released the new version.

**Pull request merged**
